databases:
  - name: easeexpense
    databaseName: ease_expense_db
    user: ease_expense_db_user

services:
  - type: web
    name: ease_expense
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easeexpense
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false